---
- hosts: localhost
  connection: local
  tasks:
      - name: "golang.yml | download golang distribution"
        get_url:
            url: "https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz"
            dest: /tmp/go.linux-amd64.tar.gz
      - name: "golang.yml | extract to /usr/local"
        unarchive:
            remote_src: yes
            src: /tmp/go.linux-amd64.tar.gz
            dest: /usr/local/
        become: yes
