---
- hosts: localhost
  connection: local
  become: true
  tasks:
      - name: "packages.yml | update all packages"
        dnf:
            name: "*"
            state: latest
      - name: "packages.yml | install rpmfusion repos"
        dnf:
            name: "{{item}}"
            state: present
        with_items:
            - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-28.noarch.rpm"
            - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-28.noarch.rpm"
      - name: "packages.yml | install repos"
        copy:
            src: "{{item.src}}"
            dest: "{{item.dest}}" 
        with_items:
            - src: kubernetes.repo
              dest: /etc/yum.repos.d/kubernetes.repo
            - src: vscode.repo
              dest: /etc/yum.repos.d/vscode.repo
            - src: dropbox.repo
              dest: /etc/yum.repos.d/dropbox.repo
            - src: google-chrome.repo
              dest: /etc/yum.repos.d/google-chrome.repo
            - src: docker-ce.repo
              dest: /etc/yum.repos.d/docker-ce.repo
            - src: _copr_vbatts-bazel.repo
              dest: /etc/yum.repos.d/_copr_vbatts-bazel.repo
      - name: download repos and gpgs from urls
        get_url:
            url: "{{item.src}}"
            dest: "{{item.dest}}"
        with_items:
            - src: https://pkg.osquery.io/rpm/osquery-s3-rpm.repo
              dest: /etc/yum.repos.d/osquery-s3-rpm.repo
            - src: https://pkg.osquery.io/rpm/GPG
              dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-osquery
      - name: "packages.yml | install flash repo"
        dnf:
            name: "http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm"
            state: present
      - name: "packages.yml | install slack"
        dnf:
            name: "{{item}}"
            state: latest
        with_items:
            - "https://downloads.slack-edge.com/linux_releases/slack-3.2.1-0.1.fc21.x86_64.rpm"
      - name: "packages.yml | install fakehal dep pm-utils, not in fedora repos (for the movies)"
        dnf:
            name: "http://mirror.centos.org/centos/7/os/x86_64/Packages/pm-utils-1.4.1-27.el7.x86_64.rpm"
            state: present
      - name: "packages.yml | install fakehal (also for the movies)"
        dnf:
            name: "https://wtogami.fedorapeople.org/fakehal/fedora/fakehal-0.5.14-8.fc20.x86_64.rpm"
            state: present
      - name: "packages.yml | install additional packages"
        dnf:
            name: "{{item}}"
            state: latest
        with_items:
            - "git"
            - "terminator"
            - "@Development Tools"
            - "steam"
            - "libnsl.i686"
            - "mesa-dri-drivers"
            - "https://github.com/gopasspw/gopass/releases/download/v1.8.1/gopass-1.8.1-linux-amd64.rpm"
            - "kubectl"
            - "direnv"
            - "code"
            - "cmake"
            - "rdesktop"
            - "vlc"
            - "flash-plugin"
            - "gcc"
            - "gcc-c++"
            - "kernel-devel"
            - "python3"
            - "python3-devel"
            - "python-devel"
            - "ncurses-compat-libs"
            - "parcellite"
            - "google-chrome-stable"
            - "jq"
            - "xscreensaver.x86_64"
            - "xscreensaver-extras.x86_64"
            - "xscreensaver-gl-extras.x86_64"
            - "xscreensaver-extras-gss.x86_64"
            - "xscreensaver-gl-extras-gss.x86_64"
            - "rss-glx-xscreensaver.x86_64"
            - "nautilus-dropbox"
            - "docker-ce"
            - "bazel"
            - "meld"
            - "HandBrake"
            - "HandBrake-gui"
            - "osquery"
            - "minicom"
        tags:
            - install_pkgs
