---
- hosts: localhost
  connection: local
  become: true
  tasks:
      - name: update all packages
        dnf:
            name: "*"
            state: latest
      - name: install rpmfusion repos
        dnf:
            name: "{{item}}"
            state: present
        with_items:
            - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-28.noarch.rpm"
            - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-28.noarch.rpm"
      - name: install kubernetes repo
        copy:
            src: kubernetes.repo
            dest: /etc/yum.repos.d/kubernetes.repo
      - name: install vs code repo
        copy:
            src: vscode.repo
            dest: /etc/yum.repos.d/vscode.repo
      - name: install flash repo
        dnf:
            name: "http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm"
            state: present
      - name: install slack
        dnf:
            name: "{{item}}"
            state: latest
        with_items:
            - "https://downloads.slack-edge.com/linux_releases/slack-3.2.1-0.1.fc21.x86_64.rpm"
      - name: install fakehal dep pm-utils, not in fedora repos (for the movies)
        dnf:
            name: "http://mirror.centos.org/centos/7/os/x86_64/Packages/pm-utils-1.4.1-27.el7.x86_64.rpm"
            state: present
      - name: install fakehal (also for the movies)
        dnf:
            name: "https://wtogami.fedorapeople.org/fakehal/fedora/fakehal-0.5.14-8.fc20.x86_64.rpm"
            state: present
      - name: install additional packages
        dnf:
            name: "{{item}}"
            state: latest
        with_items:
            - "git"
            - "terminator"
            - "@Development Tools"
            - "steam"
            - "https://github.com/gopasspw/gopass/releases/download/v1.8.1/gopass-1.8.1-linux-amd64.rpm"
            - "kubectl"
            - "direnv"
            - "code"
            - "cmake"
            - "rdesktop"
            - "vlc"
            - "flash-plugin"
            - "gcc"
            - "gcc-c++"
            - "kernel-devel"
            - "python3-devel"
            - "python-devel"
            - "ncurses-compat-libs"
            - "parcellite"
            - "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"
        tags:
            - install_pkgs
