- hosts: localhost
  connection: local
  tasks:
      - name: "python.yml | update pip (globally)"
        pip:
            executable: pip3
            name: pip
            state: latest
        become: true
      - name: "python.yml | install pip packages"
        pip:
            executable: pip3
            extra_args: "--user"
            name:
                - ipython
                - ansible
                - awscli
                - requests
                - pipenv
                - pylint
                - yamllint
            state: latest
